# Generated by Django 4.2.30 on 2026-10-02 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0029_transmission_request_provenance'),
        ('trust', '0005_historicaltransaction_method_transaction_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='payment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='invoicing.payment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_withdrawal', to='invoicing.payment'),
        ),
    ]
