# Generated by Django 4.2.30 on 2026-10-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_customuser_tasks_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
