# Generated by Django 4.2.30 on 2026-10-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_reports_permission_off_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notify_new_intakes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='notify_new_intakes',
            field=models.BooleanField(default=False),
        ),
    ]
