# Generated by Django 4.2.30 on 2026-10-08 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_notify_new_intakes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_counter', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'app_accounts_authenticator',
            },
        ),
        migrations.CreateModel(
            name='SignInThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254, unique=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_accounts_sign_in_throttle',
            },
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='accounts_customuser_email_unique'),
        ),
        migrations.AddField(
            model_name='authenticator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authenticator', to=settings.AUTH_USER_MODEL),
        ),
    ]
