# Generated by Django 4.2.30 on 2026-10-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_firm_quick_task_ai_firm_quick_task_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='invoice_trust_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='firm',
            name='payment_terms',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
