# Generated by Django 4.2.30 on 2026-10-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_firm_invoice_wording'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='anthropic_api_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='firm',
            name='gemini_api_key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
