# Generated by Django 4.2.30 on 2026-10-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_firm_ai_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='require_authenticator',
            field=models.BooleanField(default=False),
        ),
    ]
