# Generated by Django 4.2.30 on 2026-10-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_firm_require_authenticator'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='logo_dark',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AddField(
            model_name='firm',
            name='logo_email',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
    ]
