#!/usr/bin/env python3
"""Generate the reference pages that would rot if maintained by hand.

Writes three pages under docs/reference/:

  environment.md  every variable config/settings.py reads, described by the
                  comments in config/.env.example
  commands.md     every management command, with its ``help`` text
  schedules.md    every recurring job in apps/management/schedules.py

Everything is read with ``ast`` and plain text parsing, so the script needs
neither Django nor a configured environment and runs with the standard
library alone.

Usage:
    python3 scripts/gen_docs_reference.py           # rewrite the pages
    python3 scripts/gen_docs_reference.py --check   # exit 1 if any is stale

``--check`` also fails when a variable the application reads is missing from
config/.env.example, or when .env.example lists one nothing reads.
config/tests/test_docs_reference.py runs it, so CI catches the drift in the
pull request that causes it.
"""

import argparse
import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SETTINGS = ROOT / "config" / "settings.py"
CONTEXT = ROOT / "config" / "context.py"
ENV_EXAMPLE = ROOT / "config" / ".env.example"
SCHEDULES = ROOT / "apps" / "management" / "schedules.py"
OUT_DIR = ROOT / "docs" / "reference"

HEADER = (
    "<!-- Generated by scripts/gen_docs_reference.py. Do not edit by hand: "
    "change the source it names and run the script again. -->\n\n"
)

CASTS = {"bool": "boolean", "int": "integer", "list": "comma-separated list"}


# --------------------------------------------------------------------------
# Environment variables
# --------------------------------------------------------------------------


class EnvRead:
    """One variable the application reads, as found in the source."""

    def __init__(self, name, kind="text", default=None, condition=None):
        self.name = name
        self.kind = kind
        # None means there is no default: the app will not start without it.
        self.default = default
        # Source text of the enclosing ``if`` test, when the read is guarded.
        self.condition = condition


def _render_default(node):
    """Readable form of a default-value expression."""
    try:
        value = ast.literal_eval(node)
    except (ValueError, SyntaxError):
        value = None
        if isinstance(node, ast.BinOp):
            try:
                value = eval(  # noqa: S307 - arithmetic on literals only
                    compile(ast.Expression(node), "<default>", "eval"),
                    {"__builtins__": {}},
                )
            except Exception:
                value = None
        if value is None:
            source = ast.unparse(node)
            if isinstance(node, ast.Name):
                return f"the value of `{source}`"
            in_repo = re.fullmatch(r"str\(BASE_DIR / '(.+)'\)", source)
            if in_repo:
                return f"`{in_repo.group(1)}/` in the repository"
            return f"`{source}`"
    if value == "" or value == []:
        return "empty"
    return f"`{value}`"


def _env_reads_in_settings():
    """Every ``env(...)`` / ``env.bool(...)`` style read in settings.py."""
    tree = ast.parse(SETTINGS.read_text())
    reads = {}

    # environ.Env(DEBUG=(bool, False), ...) declares a cast and a default.
    declared = {}
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == "Env"
        ):
            for kw in node.keywords:
                cast, default = kw.value.elts
                kind = CASTS.get(getattr(cast, "id", ""), "text")
                declared[kw.arg] = (kind, default)

    def visit(node, condition):
        if isinstance(node, ast.If):
            test = ast.unparse(node.test)
            for child in node.body:
                visit(child, test)
            for child in node.orelse:
                visit(child, condition)
            return
        if isinstance(node, ast.Call):
            func = node.func
            is_env = isinstance(func, ast.Name) and func.id == "env"
            is_env_cast = (
                isinstance(func, ast.Attribute)
                and isinstance(func.value, ast.Name)
                and func.value.id == "env"
            )
            if (is_env or is_env_cast) and node.args:
                name = ast.literal_eval(node.args[0])
                kind = CASTS.get(func.attr, "text") if is_env_cast else "text"
                default = None
                for kw in node.keywords:
                    if kw.arg == "default":
                        default = _render_default(kw.value)
                if name in declared:
                    kind, declared_default = declared[name]
                    if default is None:
                        default = _render_default(declared_default)
                reads.setdefault(name, EnvRead(name, kind, default, condition))
        for child in ast.iter_child_nodes(node):
            visit(child, condition)

    visit(tree, None)
    return reads


def _env_reads_in_context():
    """``os.environ.get("X")`` reads in config/context.py."""
    reads = {}
    for node in ast.walk(ast.parse(CONTEXT.read_text())):
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == "get"
            and ast.unparse(node.func.value) == "os.environ"
        ):
            name = ast.literal_eval(node.args[0])
            reads[name] = EnvRead(name, default="empty")
    return reads


def env_reads():
    reads = _env_reads_in_context()
    reads.update(_env_reads_in_settings())
    return reads


SECTION_RE = re.compile(r"^# === (.+) ===$")
VAR_RE = re.compile(r"^(# )?([A-Z][A-Z0-9_]*)=(.*)$")


def env_example_sections():
    """``[(title, [(name, description), ...]), ...]`` from .env.example."""
    sections = []
    comment = []
    for line in ENV_EXAMPLE.read_text().splitlines():
        section = SECTION_RE.match(line)
        var = VAR_RE.match(line)
        if section:
            sections.append((section.group(1), []))
            comment = []
        elif var:
            if sections:
                sections[-1][1].append((var.group(2), " ".join(comment)))
            comment = []
        elif line.startswith("#"):
            comment.append(line.lstrip("#").strip())
        else:
            comment = []
    return sections


def env_problems():
    """Mismatches between what the app reads and what .env.example lists."""
    read = set(env_reads())
    listed = {name for _, rows in env_example_sections() for name, _ in rows}
    problems = []
    for name in sorted(read - listed):
        problems.append(f"{name} is read by the app but missing from .env.example")
    for name in sorted(listed - read):
        problems.append(f"{name} is in .env.example but nothing reads it")
    for _, rows in env_example_sections():
        for name, description in rows:
            if not description:
                problems.append(f"{name} has no comment above it in .env.example")
    return problems


def _cell(text):
    return text.replace("|", "\\|")


def render_environment():
    reads = env_reads()
    out = [
        "# Environment variables",
        "",
        "Kosmos is configured through `config/.env`, the only file it reads.",
        "This page lists every variable. How to create the file is covered in",
        "[Configuration](../admin/configuration.md).",
        "",
        "**Required** means there is no default and the application will not",
        "start without a value. A default of *empty* means the feature the",
        "variable belongs to stays off or falls back until it is set.",
        "",
    ]
    for title, rows in env_example_sections():
        out += [
            f"## {title}",
            "",
            "| Variable | Default | Description |",
            "|---|---|---|",
        ]
        for name, description in rows:
            read = reads.get(name)
            if read is None:
                continue
            if read.default is None:
                default = "**Required**"
                if read.condition:
                    default = f"**Required** when `{read.condition}`"
            else:
                default = read.default
            if read.kind != "text":
                description = f"{description} ({read.kind})".strip()
            out.append(f"| `{name}` | {_cell(default)} | {_cell(description)} |")
        out.append("")
    return HEADER + "\n".join(out).rstrip("\n") + "\n"


# --------------------------------------------------------------------------
# Management commands
# --------------------------------------------------------------------------


def _command_help(path):
    """The ``help`` class attribute of a management command module."""
    for node in ast.walk(ast.parse(path.read_text())):
        if isinstance(node, ast.ClassDef) and node.name == "Command":
            for stmt in node.body:
                if (
                    isinstance(stmt, ast.Assign)
                    and getattr(stmt.targets[0], "id", "") == "help"
                ):
                    try:
                        return " ".join(str(ast.literal_eval(stmt.value)).split())
                    except (ValueError, SyntaxError):
                        return ""
    return ""


def render_commands():
    by_app = {}
    for path in sorted(ROOT.glob("apps/*/management/commands/*.py")):
        if path.name.startswith("_"):
            continue
        app = path.parts[-4]
        by_app.setdefault(app, []).append((path.stem, _command_help(path)))

    out = [
        "# Management commands",
        "",
        "Kosmos's own `manage.py` commands, grouped by the app that defines",
        "them. Run one with `python manage.py <command>`, and add `--help` to",
        "see its arguments.",
        "",
        "Which of these an operator needs, and when, is covered in",
        "[Background worker](../admin/worker.md#management-commands-an-operator-uses).",
        "",
    ]
    for app in sorted(by_app):
        out += [f"## {app}", "", "| Command | What it does |", "|---|---|"]
        for name, help_text in sorted(by_app[app]):
            out.append(f"| `{name}` | {_cell(help_text)} |")
        out.append("")
    return HEADER + "\n".join(out).rstrip("\n") + "\n"


# --------------------------------------------------------------------------
# Schedules
# --------------------------------------------------------------------------

DAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]


def _expand_days(field):
    days = set()
    for part in field.split(","):
        if "-" in part:
            start, end = part.split("-")
            days.update(range(int(start), int(end) + 1))
        else:
            days.add(int(part) % 7)
    return days


def describe_cron(cron):
    """Plain words for the cron shapes the schedule registry uses."""
    minute, hour, dom, month, dow = cron.split()
    if dom != "*" or month != "*":
        return cron
    if hour == "*" and dow == "*":
        if minute == "*":
            return "Every minute"
        if re.fullmatch(r"\*/\d+", minute):
            return f"Every {minute[2:]} minutes"
        if minute.isdigit():
            return f"Hourly at {int(minute):02d} minutes past"
        return cron
    if not (minute.isdigit() and hour.isdigit()):
        return cron
    at = f"{int(hour):02d}:{int(minute):02d}"
    if dow == "*":
        return f"Daily at {at}"
    try:
        days = _expand_days(dow)
    except ValueError:
        return cron
    if len(days) == 6:
        missing = DAYS[(set(range(7)) - days).pop()]
        return f"Daily except {missing} at {at}"
    names = ", ".join(DAYS[d] for d in sorted(days))
    return f"{names} at {at}"


def schedule_specs():
    """``[(name, func, cron, description), ...]`` from schedules.py."""
    tree = ast.parse(SCHEDULES.read_text())
    specs = []
    for func in ast.walk(tree):
        if not (isinstance(func, ast.FunctionDef) and func.name == "schedule_specs"):
            continue
        # Parameter defaults, to resolve f-string crons such as
        # f"{auto_summary_time} * * 1".
        names = [a.arg for a in func.args.args]
        defaults = dict(
            zip(names[-len(func.args.defaults) :], func.args.defaults, strict=True)
            if func.args.defaults
            else []
        )
        for node in ast.walk(func):
            if not (
                isinstance(node, ast.Call)
                and getattr(node.func, "id", "") == "ScheduleSpec"
            ):
                continue
            values = []
            for arg in node.args:
                if isinstance(arg, ast.JoinedStr):
                    text = ""
                    for part in arg.values:
                        if isinstance(part, ast.Constant):
                            text += part.value
                        else:
                            text += ast.literal_eval(defaults[part.value.id])
                    values.append(text)
                else:
                    values.append(ast.literal_eval(arg))
            description = ""
            for kw in node.keywords:
                if kw.arg == "description":
                    description = ast.literal_eval(kw.value)
            specs.append((*values, description))
    return specs


def render_schedules():
    out = [
        "# Scheduled jobs",
        "",
        "Recurring jobs run by the background worker (`qcluster`). They are",
        "created or updated by `python manage.py setup_schedules`, which is",
        "safe to run again at any time, and they do nothing unless the worker",
        "is running.",
        "",
        "Times are in the server's configured time zone (`TIME_ZONE` in",
        "`config/settings.py`). The two AI summary jobs share a start time",
        "that `setup_schedules --auto-summary-time` can change; the default",
        "is shown.",
        "",
        "| Job | When | What it does |",
        "|---|---|---|",
    ]
    for name, _func, cron, description in schedule_specs():
        when = describe_cron(cron)
        if when != cron:
            when = f"{when} (`{cron}`)"
        else:
            when = f"`{cron}`"
        out.append(f"| `{name}` | {when} | {_cell(description)} |")
    out += ["", "## What each job runs", "", "| Job | Function |", "|---|---|"]
    for name, func, _cron, _description in schedule_specs():
        out.append(f"| `{name}` | `{func}` |")
    return HEADER + "\n".join(out).rstrip("\n") + "\n"


# --------------------------------------------------------------------------


PAGES = {
    "environment.md": render_environment,
    "commands.md": render_commands,
    "schedules.md": render_schedules,
}


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing; exit 1 if a page is stale or .env.example has drifted",
    )
    args = parser.parse_args()

    problems = env_problems()
    for name, render in PAGES.items():
        path = OUT_DIR / name
        text = render()
        if args.check:
            if not path.exists() or path.read_text() != text:
                problems.append(
                    f"docs/reference/{name} is out of date; "
                    "run python3 scripts/gen_docs_reference.py"
                )
        else:
            path.write_text(text)
            print(f"wrote docs/reference/{name}")

    for problem in problems:
        print(f"error: {problem}", file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
