# Generated by Django 4.2.30 on 2026-10-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0054_backfill_matter_date_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmatter',
            name='gmail_label_id',
        ),
        migrations.RemoveField(
            model_name='matter',
            name='gmail_label_id',
        ),
    ]
