# Generated by Django 4.2.30 on 2026-10-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_gmailaccount_remove_email_unique_email_per_matter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GmailSyncState',
        ),
    ]
